# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7077fd903522b92d53d8a3fa40e8b0ff3f91ea3ed5fcab2cf15bc59e56a113eb4ce0d03ee849dfda3177f384ac518bca0261f8727442b584bc0415e790c9e145

test:
  secret_key_base: d338f483c581f0b6ce0bd34230e72b91b023bf05ffff4b98e54a66a45b153b061af9408c399259886ffc997e40c01e6f846ec943d4b000b1ce68c4ffe9b0a6fb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
